import {
  ArrowRight,
  Building2,
  Calendar,
  CheckCircle2,
  ChevronRight,
  ClipboardCheck,
  Facebook,
  FlaskConical,
  Globe,
  GraduationCap,
  Home,
  Instagram,
  Lightbulb,
  Link as LinkIconLucide,
  Linkedin,
  Mail,
  Menu,
  Phone,
  Play,
  Puzzle,
  Rocket,
  SearchCheck,
  Sparkles,
  Star,
  TrendingUp,
  Users,
  X,
} from 'lucide-react'

const iconMap = {
  AcademicCapIcon: GraduationCap,
  ArrowRightIcon: ArrowRight,
  ArrowTrendingUpIcon: TrendingUp,
  ArrowUpRightIcon: ChevronRight,
  Bars3Icon: Menu,
  BeakerIcon: FlaskConical,
  BuildingOffice2Icon: Building2,
  CalendarIcon: Calendar,
  CheckCircleIcon: CheckCircle2,
  ClipboardDocumentCheckIcon: ClipboardCheck,
  DocumentMagnifyingGlassIcon: SearchCheck,
  EnvelopeIcon: Mail,
  FacebookIcon: Facebook,
  GlobeAltIcon: Globe,
  HomeIcon: Home,
  InstagramIcon: Instagram,
  LightBulbIcon: Lightbulb,
  LinkedInIcon: Linkedin,
  LinkIcon: LinkIconLucide,
  PhoneIcon: Phone,
  PlayIcon: Play,
  PuzzlePieceIcon: Puzzle,
  RocketLaunchIcon: Rocket,
  SparklesIcon: Sparkles,
  StarIcon: Star,
  UserGroupIcon: Users,
  XMarkIcon: X,
}

export function AppIcon({ name, size = 24, className = '', strokeWidth = 2, ...props }) {
  const Icon = iconMap[name] ?? Sparkles

  return <Icon size={size} strokeWidth={strokeWidth} className={className} {...props} />
}